"use client";

import classNames from "classnames/bind";
import Link from "next/link";
import { Backlink } from "@/ui/Backlink";
import cls from "./page.module.scss";
import {
  useSelectedLayoutSegment,
  useSearchParams,
  useSelectedLayoutSegments,
} from "next/navigation";

const cn = classNames.bind(cls);

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function AuthLayout({ children }: { children: React.ReactNode }) {
  const activePage = useSelectedLayoutSegment();
  const pathsArr = useSelectedLayoutSegments();

  const isAuth = activePage === null;
  const isRegister = activePage === "register" || activePage === "sms-code";
  const isRecovery = pathsArr[pathsArr.length - 1] === "recovery";

  return (
    <div className={cls.authPage}>
      {activePage !== "forgot-password" && !isRecovery ? (
        <nav className={cls.authPage_nav}>
          <Link
            className={cn(cls.authPage_navItem, { authPage_navItem_active: isAuth })}
            href="/auth"
          >
            Вход
          </Link>

          <Link
            className={cn(cls.authPage_navItem, { authPage_navItem_active: isRegister })}
            href="/auth/register"
          >
            Регистрация
          </Link>
        </nav>
      ) : (
        <Backlink className={cls.authPage_backLink} alwaysShow={true} />
      )}
      {children}
    </div>
  );
}
